config/routes.rb
Rails.application.routes.draw do

  

 

  namespace :admin do
    resources :users
    resources :devices
   resources :notifications 
  end
  
resources :admin

resources :setups

resources :locations do
  collection do
    post 'get_last_location'
  end
end

resources :geo_fences
resources :notifications

  resources :products

  devise_for :users
  get 'home/index'
  get 'home/playback'

  root to: "home#index"

  namespace :api do 
    get '/locations' => 'api#create_location'
  end

  resources :users do 
    collection do 
      get :notification
    end
  end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.is? :admin
      can :manage, :all
    else
      can :read, :all
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/device.rb
class Device < ActiveRecord::Base
  has_many :locations
  
  has_many :device_notifications
  has_many :notifications, through: :device_notifications
    
end

app/models/device_notification.rb
class DeviceNotification < ActiveRecord::Base
	belongs_to :notification
	belongs_to :user
end

app/models/geo_fence.rb
class GeoFence < ActiveRecord::Base
  belongs_to :user
  # has_many :locations, dependent: :destroy
  has_one :center , foreign_key: "geo_fence_id", class_name: "Location"

end

app/models/location.rb
class Location < ActiveRecord::Base
  belongs_to :device
  belongs_to :geo_fence
end

app/models/notification.rb
class Notification < ActiveRecord::Base
	has_many :device_notifications
	has_many :users, through: :device_notifications
end

app/models/product.rb
class Product < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :devices
  has_many :geo_fences

  has_many :device_notifications
  has_many :notifications, through: :device_notifications

  # accepts_nested_attributes_for :device_notifications, :reject_if => proc { |att| att.blank? }, :allow_destroy => true
  

  def is?( requested_role )
    self.role == requested_role.to_s
  end

end

app/controllers/admin/notifications_controller.rb
class Admin::NotificationsController < ApplicationController
  before_action :set_notification, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @notifications = Notification.all
    respond_with([:admin,@notifications])
  end

  def show
    respond_with(@notification)
  end

  def new
    @notification = Notification.new
    respond_with([:admin,@notification])
  end

  def edit
  end

  def create
    @notification = Notification.new(notification_params)
    @notification.save
    respond_with([:admin,@notification])
  end

  def update
    @notification.update(notification_params)
    respond_with([:admin,@notification])
  end

  def destroy
    @notification.destroy
    respond_with([:admin,@notification])
  end

  private
    def set_notification
      @notification = Notification.find(params[:id])
    end

    def notification_params
      params.require(:notification).permit(:name)
    end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_filter :authenticate_user!
	def index
	end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :authenticate_user!
  def index
    if current_user.is?("admin")
      redirect_to admin_index_path
    end
    @lat, @lng = 51.508742, -0.120850
  end

  def playback
    # binding.pry
  end
end

app/controllers/setups_controller.rb
class SetupsController < ApplicationController

	def index
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 
  def notification	
  end

  def update
  	current_user.update_attributes(user_params)
  	redirect_to notification_users_url,:notice => "User notification update"
  end

private
	def user_params
		params.require(:user).permit!#(:name, notification_ids: [])
	end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/geo_fences_helper.rb
module GeoFencesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/setups_helper.rb
module SetupsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/notifications/_form.html.erb
<%= form_for([:admin,@notification]) do |f| %>
  <% if @notification.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@notification.errors.count, "error") %> prohibited this notification from being saved:</h2>

      <ul>
      <% @notification.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/notifications/edit.html.erb
<h2>Editing notification</h2>

<%= render 'form' %>

<%= link_to 'Show', [:admin, @notification] %> |
<%= link_to 'Back', admin_notifications_path %>

app/views/admin/notifications/index.html.erb
  <div class="row">
    <div class="col-md-12">
      <!-- BEGIN EXAMPLE TABLE PORTLET-->
      <div class="portlet box blue">
        <div class="portlet-title">
          <div class="caption">
            <i class="fa fa-edit"></i>Notifications
          </div>
          <div class="tools">
            <a href="javascript:;" class="collapse">
            </a>
          </div>
        </div>
        <div class="portlet-body">
          <div class="table-toolbar">
            <div class="row">
              <div class="col-md-6">
                <div class="btn-group">
                  <a class="btn green" href="<%=new_admin_notification_path%>" data-no-turbolink=true>
                    Add New <i class="fa fa-plus"></i>
                  </a>
                </div>
              </div>
              <div class="col-md-6">
              </div>
            </div>
          </div>
          <table class="table table-striped table-hover table-bordered" id="sample_editable_15">
          <thead>
          <tr>
            <th>Name</th>
            <th>Actions</th>
          </tr>
          </thead>
          <tbody>
          <% @notifications.each do |notification| %>
          <tr >
            <td><%= notification.name %></td>
            <td><%= link_to 'Show', [:admin,notification] %>
            <%= link_to 'Edit', edit_admin_notification_path(notification) %>
            <%= link_to 'Destroy', [:admin,notification], method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
          <%end%>
          </tbody>
          </table>
        </div>
      </div>
      <!-- END EXAMPLE TABLE PORTLET-->
    </div>
  </div>
<%= javascript_include_tag "new_theme/admin/pages/scripts/new/table-editable15.js"%>
<script>
jQuery(document).ready(function() {
   TableEditable15.init();
});
</script>

app/views/admin/notifications/new.html.erb
<h2>New notification</h2>

<%= render 'form' %>

<%= link_to 'Back', admin_notifications_path %>

app/views/admin/notifications/sample_form.html.erb
<div class="portlet box blue">
  <div class="portlet-title">
    <div class="caption">
      <i class="fa fa-gift"></i> New Notification
    </div>
    <div class="tools">
      <a href="javascript:;" class="collapse">
      </a>
      <a href="#portlet-config" data-toggle="modal" class="config">
      </a>
      <a href="javascript:;" class="reload">
      </a>
      <a href="javascript:;" class="remove">
      </a>
    </div>
  </div>
  <div class="portlet-body form">
    <!-- BEGIN FORM-->
    <form action="#" class="form-horizontal">
      <div class="form-body">
        <div class="form-group">
          <label class="col-md-3 control-label">Text</label>
          <div class="col-md-4">
            <input type="text" class="form-control" placeholder="Enter text">
          </div>
        </div>
      </div>
      <div class="form-actions fluid">
        <div class="row">
          <div class="col-md-offset-3 col-md-9">
            <button type="submit" class="btn green">Submit</button>
            <button type="button" class="btn default">Cancel</button>
          </div>
        </div>
      </div>
    </form>
    <!-- END FORM-->
  </div>
</div>

app/views/admin/notifications/show.html.erb
<div class="portlet box blue">
  <div class="portlet-title">
    <div class="caption">
      <i class="fa fa-gift"></i> Notification
    </div>
    <div class="tools">
      <a href="javascript:;" class="collapse">
      </a>
      <a href="#portlet-config" data-toggle="modal" class="config">
      </a>
      <a href="javascript:;" class="reload">
      </a>
      <a href="javascript:;" class="remove">
      </a>
    </div>
  </div>
  <div class="portlet-body form">
    <!-- BEGIN FORM-->
    <form action="#" class="form-horizontal">
      <div class="form-body">
        <p id="notice"><%= notice %></p>

        <p>
          <strong>Name:</strong>
          <%= @notification.name %>
        </p>

        <%= link_to 'Edit', edit_admin_notification_path(@notification) %> |
        <%= link_to 'Back', admin_notifications_path %>
      </div>
    </form>
    <!-- END FORM-->
  </div>
</div>

app/views/notifications/_form.html.erb
<%= form_for(@notification) do |f| %>
  <% if @notification.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@notification.errors.count, "error") %> prohibited this notification from being saved:</h2>

      <ul>
      <% @notification.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/notifications/new.html.erb
<h1>New notification</h1>

<%= render 'form' %>

<%= link_to 'Back', notifications_path %>