config/routes.rb
Rails.application.routes.draw do

  

 

  namespace :admin do
    resources :users
    resources :devices
   resources :notifications 
  end
  
resources :admin

resources :setups

resources :locations do
  collection do
    post 'get_last_location'
  end
end

resources :geo_fences
resources :notifications

  resources :products

  devise_for :users
  get 'home/index'
  get 'home/playback'

  root to: "home#index"

  namespace :api do 
    get '/locations' => 'api#create_location'
  end

  resources :users do 
    collection do 
      get :notification
    end
  end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.is? :admin
      can :manage, :all
    else
      can :read, :all
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/device.rb
class Device < ActiveRecord::Base
  has_many :locations
  
  has_many :device_notifications
  has_many :notifications, through: :device_notifications
    
end

app/models/device_notification.rb
class DeviceNotification < ActiveRecord::Base
	belongs_to :notification
	belongs_to :user
end

app/models/geo_fence.rb
class GeoFence < ActiveRecord::Base
  belongs_to :user
  # has_many :locations, dependent: :destroy
  has_one :center , foreign_key: "geo_fence_id", class_name: "Location"

end

app/models/location.rb
class Location < ActiveRecord::Base
  belongs_to :device
  belongs_to :geo_fence
end

app/models/notification.rb
class Notification < ActiveRecord::Base
	has_many :device_notifications
	has_many :users, through: :device_notifications
end

app/models/product.rb
class Product < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :devices
  has_many :geo_fences

  has_many :device_notifications
  has_many :notifications, through: :device_notifications

  # accepts_nested_attributes_for :device_notifications, :reject_if => proc { |att| att.blank? }, :allow_destroy => true
  

  def is?( requested_role )
    self.role == requested_role.to_s
  end

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_filter :authenticate_user!
	def index
	end

end

app/controllers/geo_fences_controller.rb
class GeoFencesController < ApplicationController
  before_action :set_geo_fence, only: [:show, :edit, :update, :destroy]
  def index
    @geo_fences = current_user.geo_fences
  end

  def new
  end

  def create
    @geo_fence = GeoFence.new(geo_fence_params)
    @geo_fence.user_id = current_user.id
    @geo_fence.save
    save_center(params[:center], @geo_fence.id)
    # save_coordinates(params[:coordinates_array], @geo_fence.id)
  end

  def show
    @center = @geo_fence.center
    @radius = @geo_fence.radius
  end

  def destroy
    @geo_fence.destroy
    respond_to do |format|
      format.html { redirect_to geo_fences_url, notice: 'Geo Fence was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def save_center(center, geo_fence_id)
        center = center.split(",")
        lat = center[0]
        lng = center[1]
        Location.create(:lat=>lat, :lng=>lng, :geo_fence_id=>geo_fence_id)
    end

    # def save_coordinates(coordinates_array, geo_fence_id)
    #   coordinates_array.each do |c|
    #     c = c.split(",")
    #     lat = c[0]
    #     lng = c[1]
    #     Location.create(:lat=>lat, :lng=>lng, :geo_fence_id=>geo_fence_id)
    #   end
    # end

    # Use callbacks to share common setup or constraints between actions.
    def set_geo_fence
      @geo_fence = GeoFence.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def geo_fence_params
      # params.require(:geo_fence).permit(:name, :geo_fence_type, :enabled, :user_id, :locations_atttibutes => [:id, :lat, :lng])
      params.permit(:name, :geo_fence_type, :enabled, :user_id, :radius)
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :authenticate_user!
  def index
    if current_user.is?("admin")
      redirect_to admin_index_path
    end
    @lat, @lng = 51.508742, -0.120850
  end

  def playback
    # binding.pry
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!
  load_and_authorize_resource
  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :price, :description)
    end
end

app/controllers/setups_controller.rb
class SetupsController < ApplicationController

	def index
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 
  def notification	
  end

  def update
  	current_user.update_attributes(user_params)
  	redirect_to notification_users_url,:notice => "User notification update"
  end

private
	def user_params
		params.require(:user).permit!#(:name, notification_ids: [])
	end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/geo_fences_helper.rb
module GeoFencesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/setups_helper.rb
module SetupsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/geo_fences/_index.html.erb
<h1>Geo Fences Listings</h1>
<div class="row">
  <div class="col-md-12">
    <!-- BEGIN EXAMPLE TABLE PORTLET-->
    <div class="portlet box blue">
      <div class="portlet-title">
        <div class="caption">
          <i class="fa fa-edit"></i>Geo Fences
        </div>
        <div class="tools">
          <a href="javascript:;" class="collapse">
          </a>
        </div>
      </div>
      <div class="portlet-body">
        <div class="table-toolbar">
          <div class="row">
            <div class="col-md-6">
              <div class="btn-group">
                <a class="btn green" href="<%=new_geo_fence_path%>" data-no-turbolink=true>
                  Add New <i class="fa fa-plus"></i>
                </a>
              </div>
            </div>
            <div class="col-md-6">
            </div>
          </div>
        </div>
        <table class="table table-striped table-hover table-bordered" id="sample_editable_15">
        <thead>
        <tr>
          <th> Name </th>
          <th> Type </th>
<!--           <th>
             Edit
          </th> -->
          <th>
             Delete
          </th>
        </tr >
        </thead>
        <tbody>
        <%@geo_fences.each_with_index do |geo_fence,i|%>
        <tr >
          <td>
          <a href="<%= geo_fence_path(geo_fence)%>" data-no-turbolink=true>
            <%= geo_fence.name%>&nbsp;
          </a>
          </td>
          <td><%= geo_fence.geo_fence_type%></td>
<!--           <td>
            <a class="" href="javascript:;">
            Edit </a>
          </td> -->
          <td>
            <%= link_to 'Delete', geo_fence_path(geo_fence), method: :delete, data: { confirm: 'Are you sure?' } %>
          </td>
        </tr>
        <%end%>
        </tbody>
        </table>
      </div>
    </div>
    <!-- END EXAMPLE TABLE PORTLET-->
  </div>
</div>

<%= javascript_include_tag "new_theme/admin/pages/scripts/new/table-editable15.js"%>
<script>
jQuery(document).ready(function() {
   TableEditable15.init();
});
</script>

app/views/geo_fences/_new.html.erb
<span id="info"></span>
<div class="row">
  <div class="col-md-12">
    <!-- BEGIN BASIC PORTLET-->
    <div class="portlet box blue">
      <div class="portlet-title">
        <div class="caption">
          <i class="fa fa-gift"></i>New GeoFence
        </div>
        <div class="tools">
          <a href="javascript:;" class="collapse">
          </a>
          <a href="#portlet-config" data-toggle="modal" class="config">
          </a>
          <a href="javascript:;" class="reload">
          </a>
          <a href="javascript:;" class="remove">
          </a>
        </div>
      </div>
      <div class="portlet-body form">
        <input type="text" placeholder="Search Box" id="pac-input" class="form-control" style="width:40%;margin-top:10px;"></input>
          <div id="googleMap" style="width:100%;height:400px;">
          </div>
        <div class="form-actions fluid">
          <div class="row">
            <div class="col-md-offset-4 col-md-9 geo_fence_form">
              <div class="col-md-3">
                <input id="geo_fence_name" type="text" class="form-control" placeholder="Name" />
              </div>
              <div class="col-md-3">
                <input id="geo_fence_type" type="text" class="form-control" placeholder="Type" />
              </div>
<!--               <div class="col-md-3">
                <input type="text" class="form-control" name="Enabled" />
              </div> -->
              <button type="button" class="btn green" onclick="saveGeoFence();">Save</button>
              <a class="btn default" href="<%=new_geo_fence_path%>" data-no-turbolink=true>
                Cancel
              </a>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- END BASIC PORTLET-->
  </div>
</div>

<script>

  var map;
  var marker;
  var infowindow;
  var start = new google.maps.LatLng(31.528854654816588, 74.28192257881165);
  var end = new google.maps.LatLng(31.525727008258347, 74.27833914756775);

  var searchBoxLocation;

  var circle;
  var circle_center;
  var circle_radius;

  function initialize(){

    
  var mapProp = {
    center:new google.maps.LatLng(33.5190755, -111.9253654),
    zoom:12,
    mapTypeId:google.maps.MapTypeId.ROADMAP
    };

    map = new google.maps.Map(document.getElementById("googleMap"),mapProp);
    // Seeting circle first time on map
    setCircle(new google.maps.LatLng(33.5004686, -111.9027061), 20);


    /*=======================Search Box Logic=============Start========*/
    var searchBox = new google.maps.places.SearchBox(document.getElementById('pac-input'));
    map.controls[google.maps.ControlPosition.TOP_CENTER].push(document.getElementById('pac-input'));
    google.maps.event.addListener(searchBox, 'places_changed', function() {
      searchBox.set('map', null);


      var places = searchBox.getPlaces();

      var bounds = new google.maps.LatLngBounds();
      var i, place;
      for (i = 0; place = places[i]; i++) {
        (function(place) {
          // myPolygon.setMap(null);

          searchBoxLocation = place.geometry.location

          // Place found in SearchBox
          var marker = new google.maps.Marker({position:searchBoxLocation});

          // Circle Code
           circle.setMap(null);
           setCircle(searchBoxLocation, 5);


          // marker.bindTo('map', searchBox, 'map');
          google.maps.event.addListener(marker, 'map_changed', function() {
            if (!this.getMap()) {
              this.unbindAll();
            }
          });
          bounds.extend(place.geometry.location);


        }(place));

      }
      map.fitBounds(bounds);
      searchBox.set('map', map);
      map.setZoom(Math.min(map.getZoom(),15));

    });
    /*=======================Search Box Logic=============End========*/

  }

  google.maps.event.addDomListener(window, 'load', initialize);


  function setCircle(center, r){ // A method to set Circle on Map
        circle_radius = r * 100
        circle_center = center.toUrlValue(8);

        circle = new google.maps.Circle({
        center: center,
        map: map,
        radius: circle_radius,          // Meters
        fillColor: '#FF0000',
        fillOpacity: 0.3,
        strokeColor: "#FF0000",
        strokeWeight: 0,         
        editable: true,
        draggable: true
    });

    circle.setMap(map);

    google.maps.event.addListener(circle, 'center_changed', function () { //Circle Event Handler
        circle_center = circle.getCenter().toUrlValue(8);
        console.log("Center: "+circle.getCenter());
    });
    google.maps.event.addListener(circle, 'radius_changed', function () { //Circle Event Handler
        circle_radius = circle.getRadius(); // Meters
        console.log("Raduis: "+circle.getRadius());
    });
  }


  function saveGeoFence(){ // Saving to DB
    var name = $("#geo_fence_name").val();
    var type = $("#geo_fence_type").val();
    var inputs = $(".geo_fence_form").find('input');
    var errors = check_validation_errors(inputs)
    if (!errors) {
      $.ajax({
            url: '/geo_fences',
            data: {"center": circle_center, "radius": circle_radius, "name":name, "geo_fence_type":type},
            method: 'POST',
            success: function(data) {
              // alert("Created..!!");
            }
          });
      }
  }







</script>

app/views/geo_fences/_newWithPolygon.html.erb
<span id="info"></span>
<div class="row">
  <div class="col-md-12">
    <!-- BEGIN BASIC PORTLET-->
    <div class="portlet box blue">
      <div class="portlet-title">
        <div class="caption">
          <i class="fa fa-gift"></i>New GeoFence
        </div>
        <div class="tools">
          <a href="javascript:;" class="collapse">
          </a>
          <a href="#portlet-config" data-toggle="modal" class="config">
          </a>
          <a href="javascript:;" class="reload">
          </a>
          <a href="javascript:;" class="remove">
          </a>
        </div>
      </div>
      <div class="portlet-body form">
      <input type="text" placeholder="Search Box" id="pac-input" class="form-control" style="width:40%;margin-top:10px;"></input>
        <div id="googleMap" style="width:100%;height:400px;">
        </div>
        <div class="form-actions fluid">
          <div class="row">
            <div class="col-md-offset-4 col-md-9 geo_fence_form">
              <div class="col-md-3">
                <input id="geo_fence_name" type="text" class="form-control" placeholder="Name" />
              </div>
              <div class="col-md-3">
                <input id="geo_fence_type" type="text" class="form-control" placeholder="Type" />
              </div>
<!--               <div class="col-md-3">
                <input type="text" class="form-control" name="Enabled" />
              </div> -->
              <button type="button" class="btn green" onclick="saveGeoFence();">Save</button>
              <a class="btn default" href="<%=new_geo_fence_path%>" data-no-turbolink=true>
                Cancel
              </a>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- END BASIC PORTLET-->
  </div>
</div>

<script>

  var map;
  var marker;
  var infowindow;
  var start = new google.maps.LatLng(31.528854654816588, 74.28192257881165);
  var end = new google.maps.LatLng(31.525727008258347, 74.27833914756775);
  var searchBoxLocation;
  var triangleCoords;

  function initialize(){

    
  var mapProp = {
    center:new google.maps.LatLng(33.5190755, -111.9253654),
    zoom:12,
    mapTypeId:google.maps.MapTypeId.ROADMAP
    };

    map = new google.maps.Map(document.getElementById("googleMap"),mapProp);



    // Polygon Coordinates
    triangleCoords = [
    new google.maps.LatLng(33.5004686, -111.9027061),
      new google.maps.LatLng(33.5362475, -111.9267386),
      new google.maps.LatLng(33.5104882, -111.9627875),
      new google.maps.LatLng(33.5004686, -111.9027061)
    ];
    // Styling & Controls
    myPolygon = new google.maps.Polygon({
      paths: triangleCoords,
      draggable: true, // turn off if it gets annoying
      editable: true,
      strokeColor: '#FF0000',
      strokeOpacity: 0.8,
      strokeWeight: 2,
      fillColor: '#FF0000',
      fillOpacity: 0.35
    });

    var circle = new google.maps.Circle({
        center: new google.maps.LatLng(33.5004686, -111.9027061),
        map: map,
        radius: 2 * 1000,          // Meters
        fillColor: '#FF0000',
        fillOpacity: 0.3,
        strokeColor: "#FF0000",
        strokeWeight: 0,         
        editable: true,
        draggable: true
    });

    // myPolygon.setMap(map);
    circle.setMap(map);
    //google.maps.event.addListener(myPolygon, "dragend", getPolygonCoords);
    google.maps.event.addListener(myPolygon.getPath(), "insert_at", getPolygonCoords);
    //google.maps.event.addListener(myPolygon.getPath(), "remove_at", getPolygonCoords);
    google.maps.event.addListener(myPolygon.getPath(), "set_at", getPolygonCoords);



    /*=======================Search Box Logic=============Start========*/
    // var searchBox = new google.maps.places.SearchBox(document.getElementById('pac-input'));
    // map.controls[google.maps.ControlPosition.TOP_CENTER].push(document.getElementById('pac-input'));
    // google.maps.event.addListener(searchBox, 'places_changed', function() {
    //   searchBox.set('map', null);


    //   var places = searchBox.getPlaces();

    //   var bounds = new google.maps.LatLngBounds();
    //   var i, place;
    //   for (i = 0; place = places[i]; i++) {
    //     (function(place) {
    //       myPolygon.setMap(null);

    //       searchBoxLocation = place.geometry.location



    //       var marker = new google.maps.Marker({

    //         position:searchBoxLocation
    //       });


    //       marker.bindTo('map', searchBox, 'map');
    //       google.maps.event.addListener(marker, 'map_changed', function() {
    //         if (!this.getMap()) {
    //           this.unbindAll();
    //         }
    //       });
    //       bounds.extend(place.geometry.location);


    //     }(place));

    //   }
    //   map.fitBounds(bounds);
    //   searchBox.set('map', map);
    //   map.setZoom(Math.min(map.getZoom(),15));

    // });
    /*=======================Search Box Logic=============End========*/

    // triangleCoords = [];

    // triangleCoords = [
    //   new google.maps.LatLng(searchBoxLocation.lat(), searchBoxLocation.lng()),
    //   new google.maps.LatLng(searchBoxLocation.lat()+0.025, searchBoxLocation.lat()+0.025),
    //   new google.maps.LatLng(searchBoxLocation.lat()-0.025, searchBoxLocation.lat()-0.025),
    //   new google.maps.LatLng(searchBoxLocation.lat()+0.025, searchBoxLocation.lat()-0.025)
    //   // new google.maps.LatLng(33.5104882, -111.9627875),
    //   // new google.maps.LatLng(33.5004686, -111.9027061)
    // ];

    // myPolygon = new google.maps.Polygon({
    //   paths: triangleCoords,
    //   draggable: true, // turn off if it gets annoying
    //   editable: true,
    //   strokeColor: '#FF0000',
    //   strokeOpacity: 0.8,
    //   strokeWeight: 2,
    //   fillColor: '#FF0000',
    //   fillOpacity: 0.35
    // });

    // myPolygon.setMap(null);
    // myPolygon.setMap(map);

    // google.maps.event.addListener(map,'center_changed',function() {
    // // 3 seconds after the center of the map has changed, pan back to the marker
    //   window.setTimeout(function() {
    //     // map.panTo(marker.getPosition());
    //     alert("AAA")
    //   },3000);
    //   });

  }

  google.maps.event.addDomListener(window, 'load', initialize);



  var coordinates_array = []

  //Display Coordinates below map
  function getPolygonCoords() {
        coordinates_array = []
    var len = myPolygon.getPath().getLength();
    var htmlStr = "";
    for (var i = 0; i < len; i++) {
      // htmlStr += "new google.maps.LatLng(" + myPolygon.getPath().getAt(i).toUrlValue(5) + "), ";
      //Use this one instead if you want to get rid of the wrap > new google.maps.LatLng(),
      htmlStr += " " + myPolygon.getPath().getAt(i).toUrlValue(8);
        coordinates_array.push(myPolygon.getPath().getAt(i).toUrlValue(8))
    }
    document.getElementById('info').innerHTML = htmlStr;
  }

  function saveGeoFence(){ // Saving to DB
    var name = $("#geo_fence_name").val();
    var type = $("#geo_fence_type").val();
    var inputs = $(".geo_fence_form").find('input');
    var errors = check_validation_errors(inputs)
    if (!errors) {
      $.ajax({
            url: '/geo_fences',
            data: {"coordinates_array": coordinates_array, "name":name, "geo_fence_type":type},
            method: 'POST',
            success: function(data) {
              // alert("Created..!!");
            }
          });
      }
  }







</script>

app/views/geo_fences/_show.html.erb
<span id="info"></span>
<div class="row">
  <div class="col-md-12">
    <!-- BEGIN BASIC PORTLET-->
    <div class="portlet box blue">
      <div class="portlet-title">
        <div class="caption">
          <i class="fa fa-gift"></i>GeoFence <span id="counter"></span>
        </div>
        <div class="tools">
          <a href="javascript:;" class="collapse">
          </a>
          <a href="#portlet-config" data-toggle="modal" class="config">
          </a>
          <a href="javascript:;" class="reload">
          </a>
          <a href="javascript:;" class="remove">
          </a>
        </div>
      </div>
      <div class="portlet-body form">
        <div id="googleMap" style="width:100%;height:400px;">
        </div>
      </div>
    </div>
    <!-- END BASIC PORTLET-->
  </div>
</div>


<script>

  var map;
  var marker;
  var infowindow;
  var circle;
  var circle_center = new google.maps.LatLng("<%=@center.lat%>", "<%=@center.lng%>");
  var circle_radius;

  function initialize(){

    
  var mapProp = {
    center:circle_center,
    zoom:15,
    mapTypeId:google.maps.MapTypeId.ROADMAP
    };

    map = new google.maps.Map(document.getElementById("googleMap"),mapProp);
    circle = new google.maps.Circle({
    center: circle_center,
    map: map,
    radius: <%=@radius%>,          // Meters
    fillColor: '#FF0000',
    fillOpacity: 0.3,
    strokeColor: "#FF0000",
    strokeWeight: 0,
    title:"Hello World!"
    });
    circle.setMap(map);
  }

  google.maps.event.addDomListener(window, 'load', initialize);

</script>

app/views/geo_fences/create.js.erb
alert("Geo Fence Created Successfully.")

app/views/geo_fences/index.html.erb
    <div class="row">
      <div class="col-md-12">
        <%= render "index"%>
      </div>
    </div>

app/views/geo_fences/new.html.erb
<div class="row">
  <div class="col-md-12">
    <%= render "new"%>
  </div>
</div>

app/views/geo_fences/show.html.erb
<div class="row">
  <div class="col-md-12">
    <%= render "show"%>
  </div>
</div>