config/routes.rb
Rails.application.routes.draw do

  

 

  namespace :admin do
    resources :users
    resources :devices
   resources :notifications 
  end
  
resources :admin

resources :setups

resources :locations do
  collection do
    post 'get_last_location'
  end
end

resources :geo_fences
resources :notifications

  resources :products

  devise_for :users
  get 'home/index'
  get 'home/playback'

  root to: "home#index"

  namespace :api do 
    get '/locations' => 'api#create_location'
  end

  resources :users do 
    collection do 
      get :notification
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :devices
  has_many :geo_fences

  has_many :device_notifications
  has_many :notifications, through: :device_notifications

  # accepts_nested_attributes_for :device_notifications, :reject_if => proc { |att| att.blank? }, :allow_destroy => true
  

  def is?( requested_role )
    self.role == requested_role.to_s
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
	  before_action :set_user, only: [:show, :edit, :update, :destroy]
	  before_filter :authenticate_user!
		def index
		end

		def index
			@users = User.all
		end

		def new	
			@user = User.new
		end

		def create
			@user = User.new(user_params)

			respond_to do |format|
			  if @user.save
			    format.html { redirect_to admin_user_path(@user), notice: 'User was successfully created.' }
			  else
			    format.html { render :new } # asdfasdf
			  end
			end
		end

		def show	
		end

		def edit
		end

		def update
		  respond_to do |format|
		    if @user.update(user_params)
		      format.html { redirect_to admin_user_path(@user), notice: 'User was successfully updated.' }
		    else
		      format.html { render :edit } # asdfasdf
		    end
		  end
		end

		def destroy
			binding.pry
		  @user.destroy
		  respond_to do |format|
		    format.html { redirect_to admin_users_path, notice: 'User was successfully destroyed.' }
		  end
		end


		private

		def set_user
		  @user = User.find(params[:id])
		end

		def user_params
		  params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :contact_no)
		end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 
  def notification	
  end

  def update
  	current_user.update_attributes(user_params)
  	redirect_to notification_users_url,:notice => "User notification update"
  end

private
	def user_params
		params.require(:user).permit!#(:name, notification_ids: [])
	end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.erb
<%= form_for(@user, url: admin_users_path) do |f| %>

<div><%= f.label :first_name %><br />
  <%= f.text_field :first_name  %></div>

<div><%= f.label :last_name %><br />
<%= f.text_field :last_name  %></div>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password, autocomplete: "off" %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation, autocomplete: "off" %>
  </div>

  <div><%= f.label :contact_no %><br />
    <%= f.text_field :contact_no  %></div>
    <br>

  <div class="actions">
    <%= f.submit "Create User" %>
  </div>
<% end %>

app/views/admin/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', admin_user_path(@user) %> |
<%= link_to 'Back', admin_users_path %>

app/views/admin/users/index.html.erb
<h1>Listing Users</h1>

<table border="1">
  <thead>
    <tr>
      <th>User ID</th>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Email</th>
      <th>Contact No.</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.id %></td>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.email %></td>
        <td><%= user.contact_no %></td>
        <td><%= link_to 'Show', admin_user_path(user) %></td>
        <td><%= link_to 'Edit',  edit_admin_user_path(user) %></td>
        <td><%= link_to 'Destroy', admin_user_path(user), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_admin_user_path %>

app/views/admin/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_users_path %>

app/views/admin/users/show.html.erb
<p>
  <strong>First Name:</strong>
  <%= @user.first_name%>
</p>

<p>
  <strong>Last Name:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Contact No:</strong>
  <%= @user.contact_no %>
</p>

<%= link_to 'Edit',  edit_admin_user_path(@user) %> |
<%= link_to 'Back', admin_users_path %>